### ISSUE TITLE
Fails to build on Jet

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow-utils#10]
The GFS-utils fails to build on Jet with a CMake error that gempak's include directory cannot be determined.  The gempak include directory on Jet is located in /apps/gempak/7.4.2-gfortran/gempak/include, which is essentially the same as Hera (/apps/gempak/7.4.2/gempak/include).  I have updated the version of CMake to 3.20.1 in the modulefiles to no avail.  Interestingly, the gempak libraries are found correctly.

**Comment by aerorahul** [comment]
@DavidHuber-NOAA Please see the branch [feature/consistent](https://github.com/NOAA-EMC/gfs-utils/tree/feature/consistent)
I recently fixed a few bugs (and disabled GEMPAK). There is no need to run GEMPAK in dev. mode.
BTW, @KateFriedman-NOAA is currently testing this branch in one of her works.

**Comment by DavidHuber-NOAA** [comment]
@aerorahul Thanks for the heads up.  It looks like jet needs g2/3.4.5 installed under hpc-stack to support this.  I'll make that request on hpc-stack and give this a test build.
