### ISSUE TITLE
Use module reset on R&Ds

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow-utils#13]
Instead of using `module purge` on the R&D machines (Hera/Orion/Jet), use `module reset` for a cleaner build environment. Since `module reset` doesn't work out-of-the-box on those machines also set `export LMOD_SYSTEM_DEFAULT_MODULES=contrib` as a workaround to use `module reset`. This workaround was tested, discussed with, and approved by Hera sysadmin.

```
-bash-4.2$ module reset
The system default contains no modules
  (env var: LMOD_SYSTEM_DEFAULT_MODULES is empty)
  No changes in loaded modules

-bash-4.2$ export LMOD_SYSTEM_DEFAULT_MODULES=contrib
-bash-4.2$ module reset
Resetting modules to system default. Reseting $MODULEPATH back to system default. All extra directories will be 
removed from $MODULEPATH.
```

Update Hera and Orion blocks in `ush/module-setup.sh`.

**Comment by KateFriedman-NOAA** [comment]
Created `feature/module-reset-rds` branch for this work.

**Comment by KateFriedman-NOAA** [comment]
@DavidHuber-NOAA Does `module reset` work on S4?

**Comment by DavidHuber-NOAA** [comment]
@KateFriedman-NOAA Yes, it does, thanks.

**Comment by KateFriedman-NOAA** [comment]
@DavidHuber-NOAA Awesome! So it works without the hack needed for the other machines?

I will also change the S4 `module purge` to `module reset` in `ush/module-setup.sh` then. Any objections?

**Comment by DavidHuber-NOAA** [comment]
@KateFriedman-NOAA Oops.  I see what you mean now.  The command executes, but it returns the same message you are seeing on Orion and Hera and does not actually reset the modules.  Hmm...  The best module I can think of to set `LMOD_SYSTEM_DEFAULT_MODULES` to is license_intel.  Let's go with that for now and I may write a dummy module later that essentially does nothing.

**Comment by KateFriedman-NOAA** [comment]
@DavidHuber-NOAA Ok no worries! What is the exact hack command for S4 then?

```
export LMOD_SYSTEM_DEFAULT_MODULES=license_intel
module reset
```

^ this?

**Comment by KateFriedman-NOAA** [comment]
@DavidHuber-NOAA I'm going to make a similar change for the Jet block in `ush-module-setup.sh` but I know gfs-utils doesn't build on Jet currently so I can't test that update yet. Just a heads up.

**Comment by DavidHuber-NOAA** [comment]
> @DavidHuber-NOAA Ok no worries! What is the exact hack command for S4 then?
> 
> ```
> export LMOD_SYSTEM_DEFAULT_MODULES=license_intel
> module reset
> ```
> 
> ^ this?

@KateFriedman-NOAA Yes, exactly.

And thanks for the heads up on Jet.

**Comment by KateFriedman-NOAA** [comment]
@DavidHuber-NOAA I updated the S4 block of `module-setup.sh` to use `module reset` and the `LMOD_SYSTEM_DEFAULT_MODULES` hack. Committed to the `feature/module-reset-rds` branch @ [92a5d1a](https://github.com/NOAA-EMC/gfs-utils/commit/92a5d1a357c7360b2d628d550cbf144b06190980). Would you mind testing the build of this branch on S4? Thanks!

**Comment by DavidHuber-NOAA** [comment]
@KateFriedman-NOAA The gfsutils_s4.lua module has a load for cmake/3.20.1, which doesn't exist on S4 (I opened #12 to fix this).  After removing the cmake lines from gfsutils_s4.lua, gfs-utils builds successfully.

**Comment by KateFriedman-NOAA** [comment]
Noted, thanks @DavidHuber-NOAA !
