### ISSUE TITLE
Use EPIC-maintained hpc-stacks on RDHPCS

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow-utils#18]
The current hpc-stack installs are frozen. Management of hpc-stack installs on the RDHPCS platforms has moved to EPIC. Update gfs-utils to use the EPIC-installed hpc-stacks on Hera, Orion, and Jet.

Matching global-workflow issue https://github.com/NOAA-EMC/global-workflow/issues/1311

**Comment by aerorahul** [comment]
This will be superseded by the use of spack-stack.
@DavidHuber-NOAA is working on that.

See issue #23

**Comment by KateFriedman-NOAA** [comment]
Has been superseded by work completed in issue #23. Closing.
