### ISSUE TITLE
update gfs_bufr codes

### ISSUE THREAD

**Issue by BoCui-NOAA** [NOAA-EMC/global-workflow-utils#20]
The gfs-utils doesn't have the latest gfs_bufr codes.  Update gfs_bufr.fd using the latest version from gfs-v16, 
as well as fix global-workflow issue  https://github.com/NOAA-EMC/global-workflow/issues/1245

PR https://github.com/NOAA-EMC/gfs-utils/pull/19

**Comment by KateFriedman-NOAA** [comment]
Complete via #19. Closing.
