### ISSUE TITLE
Contribute back to gfs_utils

### ISSUE THREAD

**Issue by weihuang-jedi** [NOAA-EMC/global-workflow-utils#63]
### What new functionality do you need?

Need access to gfs_utils to contribute back.

### What are the requirements for the new functionality?

Need access to gfs_utils to contribute back.

### Acceptance Criteria

can create branch and merge into branch and then create PR.

### Suggest a solution (optional)

My name is Wei Huang, at EPIC, working on implementing global-workflow to NOAA-clound/parallelworks. When created a branch, and tried to merge back, got error:

[Wei.Huang@NOAA-AWS:/contrib/Wei.Huang/dev/gfs-utils/modulefiles]$ git push origin wei-epic-aws
Warning: Permanently added 'github.com,140.82.114.3' (ECDSA) to the list of known hosts.
ERROR: Permission to NOAA-EMC/gfs-utils.git denied to weihuang-jedi.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by WalterKolczynski-NOAA** [comment]
User has been instructed how to contribute without granting write access to the authoritative repo.
