### ISSUE TITLE
Compile gfs_utils on Gaea-C5

### ISSUE THREAD

**Issue by DavidBurrows-NCO** [NOAA-EMC/global-workflow-utils#66]
### What new functionality do you need?

Compiling gfs_utils on Gaea-C5

### What are the requirements for the new functionality?

NA

### Acceptance Criteria

Successful compilation on Gaea-C5

### Suggest a solution (optional)

Add/update module files for Gaea-C5

**Comment by aerorahul** [comment]
closed via #67
