### ISSUE TITLE
Spurious line in tripolar to regular interpolation

### ISSUE THREAD

**Issue by AminIlia-NOAA** [NOAA-EMC/global-workflow-utils#83]
### What is wrong?

There is a spurious line for low resolution model in the interpolated SST grid in very low latitudes. The main reason for this issue unclear (could be due to masking issue in SST parameter in model or problem in weighting functions in my view).

To resolve this issue, I submitted a PR for changing minlat in  to -78.0 as the ocean edge start from this latitude. This will mask the spurious results for these latitudes. 

@LydiaStefanova-NOAA @NeilBarton-NOAA @DeniseWorthen 
  
![image](https://github.com/user-attachments/assets/c6265713-0aa1-4211-8035-6e3f7b9b5f4c)

### What should have happened?

Change minlat to -78 in masking_mod.F90

### What machines are impacted?

All or N/A

### Steps to reproduce

change minlat in masking_mod.F90 to -78.0 to remove spurious results from interpolated grid

### Additional information

change minlat in masking_mod.F90 to -78.0 to remove spurious results from interpolated grid

### Do you have a proposed solution?

Yes

**Comment by aerorahul** [comment]
Closed via #84
